### ISSUE TITLE
Building vicare-cairo on Ubuntu 14.04

### ISSUE THREAD

**Issue by doug719** [marcomaggi/vicare-cairo#1]
1. Had to install libtool
2. On make got an error that could not find version.texi.  Corrected with
           ./configure --enable-maintainer-mode

**Comment by marcomaggi** [comment]
Indeed the readme file could be better.  Notice though that this project is just an old stub; I never got around to actually implementing the interface.  The whole thing should be updated to a recent infrastructure (things have changed).  I am busy with core development so this project is far in the list of things to do.  Sorry.
